version: '3.1'
services:
  db:
    image: postgres:9.6
    container_name: pg-lottery-db
    environment:
      - POSTGRES_DB=lottery-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - .docker/dev_data:/var/lib/postgresql
          
# volumes:
#   dev_data: